server:
  port: 8080
spring:
  profiles:
    active: prod

mybatis-plus:
  # resource的classpath:/mapper/*Mapper.xml
  mapper-locations: classpath*:/mappers/*Mapper.xml
  #别名
  typeAliasesPackage: model.com.project.system.mode
  global-config:
    #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
    id-type: 2
    #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
    field-strategy: NOT_EMPTY
    #下划线
    db-column-underline: true
    #mapper
    refresh-mapper: true
  configuration:
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
